sudo: required
services:
  - docker

before_install:
  - docker build -t praveenda99/project-repo -f Dockerfile.dev .

script:
  - docker run praveenda99/project-repo npm run test -- --coverage 
                    

